
CREATE TABLE T_GROUP
       (
       F_ID INTEGER NOT NULL AUTO_INCREMENT,
       F_NUM INTEGER NOT NULL,
       F_FACULT VARCHAR(100) NOT NULL,
       PRIMARY KEY (F_ID )
       )DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

CREATE TABLE T_STUDENT
       (
       F_ID INTEGER NOT NULL AUTO_INCREMENT,
       F_FIO VARCHAR(100) NOT NULL,
       F_GROUP_ID INTEGER,
       F_TYPE_STIPEND VARCHAR(50) NOT NULL,
       F_JOIN_DATE DATE NOT NULL,
       PRIMARY KEY (F_ID ),
       FOREIGN KEY (F_GROUP_ID) REFERENCES T_GROUP(F_ID)
       )ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;



