
CREATE TABLE T_GROUP
       (
       F_ID INTEGER NOT NULL AUTO_INCREMENT,
       F_NUM INTEGER,
       F_FACULT VARCHAR(100),
       PRIMARY KEY (F_ID )
       )ENGINE=InnoDB;

CREATE TABLE T_STUDENT
       (
       F_ID INTEGER NOT NULL AUTO_INCREMENT,
       F_FIO VARCHAR(100),
       F_GROUP_ID INTEGER,
       F_TYPE_STIPEND VARCHAR(50),
       PRIMARY KEY (F_ID ),
       FOREIGN KEY (F_GROUP_ID) REFERENCES T_GROUP(F_ID)
       );



